time,filename,pathname,exception name,exception data,error report filename
Thu Dec 29 17:31:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.OSError,[Errno 2] No such file or directory: '../data/cache',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-31-53-90030.html
Thu Dec 29 17:43:41 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.OSError,[Errno 2] No such file or directory: '../../site/stylesheets',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-43-41-43668.html
Thu Dec 29 17:44:09 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.RuntimeError,"Error: Error in XQuery expression: parse error, unexpected $, line 1, column 27",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-44-09-98891.html
Thu Dec 29 17:44:56 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.RuntimeError,"Error: Error in XQuery expression: parse error, unexpected $, line 1, column 27",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-44-56-59383.html
Thu Dec 29 17:45:05 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-45-05-35458.html
Thu Dec 29 17:57:43 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Main.py, line 20)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-57-43-67250.html
Thu Dec 29 17:58:09 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'XMLFragment' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-58-09-60187.html
Thu Dec 29 17:58:55 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'libxml2' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-58-55-42033.html
Thu Dec 29 17:59:18 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,iteration over non-sequence,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-17-59-18-38148.html
Thu Dec 29 18:00:32 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,iteration over non-sequence,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-00-32-38207.html
Thu Dec 29 18:02:00 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,XMLFragment instance has no attribute 'setBase',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-02-00-43640.html
Thu Dec 29 18:22:41 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'pathInfo' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-22-41-96937.html
Thu Dec 29 18:22:54 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,_parsePathInfo() takes exactly 1 argument (2 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-22-54-68730.html
Thu Dec 29 18:26:51 2005,Main.py,../dist/servlets/restricted/Main.py,libxml2.parserError,xmlParseFile() failed,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-26-51-78453.html
Thu Dec 29 18:26:51 2005,Main.py,../dist/servlets/restricted/Main.py,libxml2.parserError,xmlParseFile() failed,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-26-51-44160.html
Thu Dec 29 18:28:18 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.RuntimeError,"Error: Error in XQuery expression: parse error, unexpected $, line 1, column 31",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-28-18-17571.html
Thu Dec 29 18:29:27 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.RuntimeError,"Error: Error in XQuery expression: parse error, unexpected $, line 1, column 31",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-29-27-92960.html
Thu Dec 29 18:40:22 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'str' object has no attribute 'db',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-40-22-95684.html
Thu Dec 29 18:40:22 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'str' object has no attribute 'db',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-40-22-52404.html
Thu Dec 29 18:45:33 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-45-33-27111.html
Thu Dec 29 18:45:46 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-45-46-51548.html
Thu Dec 29 18:47:28 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,replace() takes at least 2 arguments (1 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-47-28-72216.html
Thu Dec 29 18:47:28 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,replace() takes at least 2 arguments (1 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-18-47-28-34210.html
Thu Dec 29 19:05:17 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-19-05-17-47043.html
Thu Dec 29 19:06:16 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-29-19-06-16-85959.html
Fri Dec 30 18:09:25 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'WeblogDirectory' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-09-25-37983.html
Fri Dec 30 18:09:25 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'WeblogDirectory' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-09-25-23615.html
Fri Dec 30 18:09:50 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,__init__() takes exactly 1 argument (2 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-09-50-21958.html
Fri Dec 30 18:09:50 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,__init__() takes exactly 1 argument (2 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-09-50-47894.html
Fri Dec 30 18:10:22 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'XMLFragment' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-10-22-79044.html
Fri Dec 30 18:10:22 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'XMLFragment' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-10-22-90472.html
Fri Dec 30 18:10:51 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'libxml2' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-10-51-64376.html
Fri Dec 30 18:10:51 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'libxml2' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-10-51-15079.html
Fri Dec 30 18:11:09 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'libxml2' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-11-09-60286.html
Fri Dec 30 18:11:09 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'libxml2' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-11-09-20783.html
Fri Dec 30 18:11:16 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'Weblog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-11-16-77296.html
Fri Dec 30 18:11:17 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'Weblog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-11-17-58804.html
Fri Dec 30 18:12:11 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-12-11-48980.html
Fri Dec 30 18:16:45 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-16-45-65413.html
Fri Dec 30 18:17:30 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-17-30-93649.html
Fri Dec 30 18:18:43 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'config' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-18-43-50168.html
Fri Dec 30 18:19:02 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,configValue() takes at least 3 arguments (2 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-19-02-31293.html
Fri Dec 30 18:19:26 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-19-26-12818.html
Fri Dec 30 18:30:55 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-30-55-62755.html
Fri Dec 30 18:32:18 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-32-18-25631.html
Fri Dec 30 18:32:48 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-32-48-13080.html
Fri Dec 30 18:35:39 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-35-39-41917.html
Fri Dec 30 18:35:58 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-35-58-55869.html
Fri Dec 30 18:37:37 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,WeblogDirectory() takes exactly 1 argument (0 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-37-37-81573.html
Fri Dec 30 18:40:37 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-40-37-16145.html
Fri Dec 30 18:41:13 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (DbXslExtension.py, line 33)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-41-13-74282.html
Fri Dec 30 18:41:13 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (DbXslExtension.py, line 33)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-41-13-94930.html
Fri Dec 30 18:41:48 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,_getDatabase() takes exactly 1 argument (2 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-18-41-48-16245.html
Fri Dec 30 19:00:52 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-52-72890.html
Fri Dec 30 19:00:52 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-52-75295.html
Fri Dec 30 19:00:52 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-52-78740.html
Fri Dec 30 19:00:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-53-30986.html
Fri Dec 30 19:00:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-53-40879.html
Fri Dec 30 19:00:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-53-39035.html
Fri Dec 30 19:00:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-53-21929.html
Fri Dec 30 19:00:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-53-33557.html
Fri Dec 30 19:00:54 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'blog' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-00-54-97279.html
Fri Dec 30 19:03:41 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'pathInfo' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-41-30639.html
Fri Dec 30 19:03:41 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'pathInfo' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-41-96635.html
Fri Dec 30 19:03:41 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-41-36827.html
Fri Dec 30 19:03:42 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'pathInfo' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-42-45561.html
Fri Dec 30 19:03:42 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-42-88331.html
Fri Dec 30 19:03:42 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'pathInfo' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-42-83659.html
Fri Dec 30 19:03:42 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'pathInfo' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-42-38950.html
Fri Dec 30 19:03:42 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-42-61860.html
Fri Dec 30 19:03:43 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'pathInfo' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-03-43-13779.html
Fri Dec 30 19:04:31 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'request' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-31-26429.html
Fri Dec 30 19:04:31 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'request' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-31-68378.html
Fri Dec 30 19:04:31 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-31-74337.html
Fri Dec 30 19:04:31 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'request' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-31-22236.html
Fri Dec 30 19:04:32 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-32-97714.html
Fri Dec 30 19:04:32 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'request' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-32-56209.html
Fri Dec 30 19:04:32 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'request' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-32-15317.html
Fri Dec 30 19:04:32 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-32-21942.html
Fri Dec 30 19:04:32 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'request' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-32-46207.html
Fri Dec 30 19:04:57 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-57-37666.html
Fri Dec 30 19:04:57 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-57-75860.html
Fri Dec 30 19:04:58 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-04-58-44568.html
Fri Dec 30 19:06:52 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-06-52-65419.html
Fri Dec 30 19:06:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-06-53-27938.html
Fri Dec 30 19:06:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-06-53-39912.html
Fri Dec 30 19:08:36 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-08-36-31388.html
Fri Dec 30 19:08:37 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-08-37-25044.html
Fri Dec 30 19:08:37 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-08-37-70984.html
Fri Dec 30 19:09:52 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-09-52-88707.html
Fri Dec 30 19:09:52 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-09-52-15375.html
Fri Dec 30 19:09:53 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-09-53-93662.html
Fri Dec 30 19:13:07 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-07-85982.html
Fri Dec 30 19:13:07 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-07-44746.html
Fri Dec 30 19:13:07 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-07-65810.html
Fri Dec 30 19:13:08 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-08-84412.html
Fri Dec 30 19:13:08 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-08-44851.html
Fri Dec 30 19:13:08 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-08-64687.html
Fri Dec 30 19:13:08 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-08-72834.html
Fri Dec 30 19:13:08 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-08-89076.html
Fri Dec 30 19:13:08 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-08-54073.html
Fri Dec 30 19:13:09 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-09-73448.html
Fri Dec 30 19:13:09 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'size',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-09-47789.html
Fri Dec 30 19:13:35 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-35-92105.html
Fri Dec 30 19:13:35 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-35-89070.html
Fri Dec 30 19:13:35 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-35-42163.html
Fri Dec 30 19:13:36 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-36-49100.html
Fri Dec 30 19:13:36 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-36-36329.html
Fri Dec 30 19:13:36 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-36-57412.html
Fri Dec 30 19:13:36 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-36-22422.html
Fri Dec 30 19:13:36 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-36-97997.html
Fri Dec 30 19:13:37 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-37-27189.html
Fri Dec 30 19:13:37 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-37-54163.html
Fri Dec 30 19:13:37 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'list' object has no attribute 'length',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-13-37-50483.html
Fri Dec 30 19:14:14 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-14-14-10911.html
Fri Dec 30 19:14:14 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-14-14-75151.html
Fri Dec 30 19:14:15 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-14-15-12353.html
Fri Dec 30 19:14:43 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,unpack non-sequence,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-14-43-57597.html
Fri Dec 30 19:14:43 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,unpack non-sequence,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-14-43-90003.html
Fri Dec 30 19:14:43 2005,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,unpack non-sequence,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2005-12-30-19-14-43-47011.html
Thu Jan  5 13:13:49 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (DBXML2Database.py, line 99)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-13-13-49-73907.html
Thu Jan  5 15:24:41 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.ImportError,Failure linking new module: /Users/kstaken/Workspace/Syncato2/Binaries/lib/python2.4/site-packages/_dbxml.so: Library not loaded: libxerces-c.26.dylib
  Referenced from: /Users/kstaken/Workspace/Syncato2/Binaries/lib/python2.4/site-packages/_dbxml.so
  Reason: image not found,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-15-24-41-50556.html
Thu Jan  5 15:44:31 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'Main' object has no attribute 'weblog',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-15-44-31-91543.html
Thu Jan  5 15:49:16 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"unindent does not match any outer indentation level (DBXML2Database.py, line 246)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-15-49-16-63870.html
Thu Jan  5 16:06:17 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"expected an indented block (Weblog.py, line 50)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-16-06-17-91301.html
Thu Jan  5 16:06:18 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"expected an indented block (Weblog.py, line 50)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-16-06-18-16563.html
Thu Jan  5 16:25:14 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-16-25-14-61064.html
Thu Jan  5 16:29:19 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-16-29-19-74472.html
Thu Jan  5 16:30:49 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-16-30-49-86278.html
Thu Jan  5 16:33:57 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-05-16-33-57-34731.html
Thu Jan 12 14:44:48 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"unindent does not match any outer indentation level (Main.py, line 47)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-44-48-71497.html
Thu Jan 12 14:44:48 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"unindent does not match any outer indentation level (Main.py, line 47)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-44-48-77181.html
Thu Jan 12 14:45:28 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"unindent does not match any outer indentation level (Main.py, line 48)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-45-28-93710.html
Thu Jan 12 14:45:28 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"unindent does not match any outer indentation level (Main.py, line 48)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-45-28-59969.html
Thu Jan 12 14:47:59 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"unindent does not match any outer indentation level (Main.py, line 47)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-47-59-22155.html
Thu Jan 12 14:47:59 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.IndentationError,"unindent does not match any outer indentation level (Main.py, line 47)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-47-59-58856.html
Thu Jan 12 14:48:25 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'Router' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-48-25-31685.html
Thu Jan 12 14:48:26 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'Router' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-48-26-32542.html
Thu Jan 12 14:48:49 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,Router() takes exactly 1 argument (0 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-48-49-57288.html
Thu Jan 12 14:48:49 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,Router() takes exactly 1 argument (0 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-48-49-89383.html
Thu Jan 12 14:49:25 2006,Main.py,../dist/servlets/restricted/Main.py,libxml2.parserError,xmlParseFile() failed,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-49-25-94685.html
Thu Jan 12 14:49:25 2006,Main.py,../dist/servlets/restricted/Main.py,libxml2.parserError,xmlParseFile() failed,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-49-25-64882.html
Thu Jan 12 14:49:54 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'response' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-49-54-66067.html
Thu Jan 12 14:49:54 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'response' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-49-54-77635.html
Thu Jan 12 14:51:01 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,_Router instance has no attribute '_checkComponent',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-51-01-53848.html
Thu Jan 12 14:52:02 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,_checkComponent() takes exactly 2 arguments (3 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-14-52-02-71889.html
Thu Jan 12 15:20:27 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.TypeError,cannot concatenate 'str' and 'tuple' objects,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-15-20-27-23300.html
Thu Jan 12 15:31:09 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Router.py, line 92)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-15-31-09-80590.html
Thu Jan 12 15:31:09 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Router.py, line 92)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-15-31-09-63868.html
Thu Jan 12 16:47:45 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.ValueError,Cannot find expected servlet class 'Route' in '../dist/servlets/restricted/Route.py'.,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-16-47-45-53953.html
Thu Jan 12 16:54:38 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'XMLFragment' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-16-54-38-93524.html
Thu Jan 12 16:54:39 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'XMLFragment' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-16-54-39-34797.html
Thu Jan 12 16:55:21 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'XMLFragment' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-16-55-21-31849.html
Thu Jan 12 16:55:21 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'XMLFragment' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-16-55-21-37131.html
Thu Jan 12 16:55:58 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'Main' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-16-55-58-62497.html
Thu Jan 12 16:55:58 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,_Router instance has no attribute 'route',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-16-55-58-77726.html
Thu Jan 12 16:57:37 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'unquote' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-16-57-37-95304.html
Thu Jan 12 16:57:38 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,_Router instance has no attribute 'route',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-16-57-38-79457.html
Thu Jan 12 16:58:18 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,_Router instance has no attribute 'route',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-16-58-18-51437.html
Thu Jan 12 17:00:05 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,_Router instance has no attribute 'route',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-17-00-05-67126.html
Thu Jan 12 17:00:12 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'Site' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-17-00-12-10770.html
Thu Jan 12 17:00:12 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,_Router instance has no attribute 'route',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-17-00-12-25667.html
Thu Jan 12 17:00:47 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,_Router instance has no attribute 'route',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-17-00-47-11337.html
Thu Jan 12 18:39:27 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.SyntaxError,"invalid syntax (Router.py, line 92)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-39-27-64970.html
Thu Jan 12 18:39:28 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Framework.py, line 42)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-18-39-28-67345.html
Thu Jan 12 18:40:10 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.ImportError,cannot import name Router,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-40-10-40637.html
Thu Jan 12 18:40:11 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.ImportError,cannot import name Router,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-18-40-11-61353.html
Thu Jan 12 18:40:26 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,'Route' object has no attribute 'router',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-40-26-35437.html
Thu Jan 12 18:40:26 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'WeblogDirectory' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-18-40-26-18813.html
Thu Jan 12 18:41:40 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,__init__() takes exactly 2 arguments (1 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-41-40-94973.html
Thu Jan 12 18:42:01 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'libxml2' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-42-01-65824.html
Thu Jan 12 18:42:18 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'Site' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-42-18-86935.html
Thu Jan 12 18:42:43 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'route' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-42-43-57569.html
Thu Jan 12 18:43:14 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'route' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-43-14-49473.html
Thu Jan 12 18:43:30 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,_verifyRoute() takes exactly 2 arguments (4 given),/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-43-30-39314.html
Thu Jan 12 18:44:04 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,Router instance has no attribute 'getSite',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-44-04-14303.html
Thu Jan 12 18:44:21 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'Framework' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-44-21-38200.html
Thu Jan 12 18:44:41 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.ImportError,cannot import name Framework,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-44-41-77613.html
Thu Jan 12 18:47:11 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.ImportError,cannot import name Framework,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-47-11-62836.html
Thu Jan 12 18:47:58 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,'module' object is not callable,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-47-58-48330.html
Thu Jan 12 18:48:07 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,'module' object is not callable,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-48-07-20045.html
Thu Jan 12 18:48:29 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,dict objects are unhashable,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-48-29-34175.html
Thu Jan 12 18:49:41 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'os' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-49-41-27239.html
Thu Jan 12 18:50:14 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'os' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-50-14-52728.html
Thu Jan 12 18:51:34 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,'NoneType' object has no attribute 'name',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-51-34-64602.html
Thu Jan 12 18:52:51 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,'NoneType' object has no attribute 'name',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-52-51-93035.html
Thu Jan 12 18:53:04 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,'NoneType' object has no attribute 'name',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-53-04-54974.html
Thu Jan 12 18:54:01 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'Component' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-54-01-92018.html
Thu Jan 12 18:54:28 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'name' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-54-28-61979.html
Thu Jan 12 18:55:01 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,_Framework instance has no attribute 'sitePath',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-55-01-38489.html
Thu Jan 12 18:57:55 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'ucfirst' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-18-57-55-70624.html
Thu Jan 12 19:18:10 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'sys' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-18-10-72229.html
Thu Jan 12 19:18:25 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,cannot concatenate 'str' and 'module' objects,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-18-25-45076.html
Thu Jan 12 19:18:56 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,'module' object is not callable,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-18-56-94166.html
Thu Jan 12 19:22:50 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,Index instance has no attribute 'index',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-22-50-15574.html
Thu Jan 12 19:23:17 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,Index instance has no attribute 'index',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-23-17-62419.html
Thu Jan 12 19:23:24 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'controller' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-23-24-71639.html
Thu Jan 12 19:43:07 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,Index instance has no attribute '__call__',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-43-07-28968.html
Thu Jan 12 19:52:23 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,Index instance has no attribute 'test',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-19-52-23-99947.html
Thu Jan 12 20:12:47 2006,Route.py,../dist/servlets/restricted/Route.py,BaseDatabase.NotFoundError,,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-12-47-38997.html
Thu Jan 12 20:12:59 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.UnboundLocalError,local variable 'method' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-12-59-16903.html
Thu Jan 12 20:14:03 2006,Route.py,../dist/servlets/restricted/Route.py,BaseDatabase.NotFoundError,,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-14-03-45818.html
Thu Jan 12 20:16:17 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.KeyError,'postID',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-16-17-37811.html
Thu Jan 12 20:16:33 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.NameError,global name 'time' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-16-33-62240.html
Thu Jan 12 20:17:44 2006,Route.py,../dist/servlets/restricted/Route.py,BaseDatabase.NotFoundError,,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-17-44-98694.html
Thu Jan 12 20:19:41 2006,Route.py,../dist/servlets/restricted/Route.py,BaseDatabase.NotFoundError,,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-19-41-87392.html
Thu Jan 12 20:19:58 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,'NoneType' object is not callable,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-19-58-18609.html
Thu Jan 12 20:20:19 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,'NoneType' object has no attribute 'name',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-20-19-69147.html
Thu Jan 12 20:20:26 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.TypeError,'NoneType' object is not callable,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-20-20-26-77853.html
Thu Jan 12 21:02:23 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.AttributeError,Router instance has no attribute 'db',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-21-02-23-41727.html
Thu Jan 12 21:02:45 2006,Route.py,../dist/servlets/restricted/Route.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Route.py-2006-01-12-21-02-45-57418.html
Thu Jan 12 21:42:06 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.ValueError,Cannot find expected servlet class 'Main' in '../dist/servlets/restricted/Main.py'.,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-42-06-18103.html
Thu Jan 12 21:42:06 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.ValueError,Cannot find expected servlet class 'Main' in '../dist/servlets/restricted/Main.py'.,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-42-06-66265.html
Thu Jan 12 21:42:34 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-42-34-60650.html
Thu Jan 12 21:42:34 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-42-34-79749.html
Thu Jan 12 21:50:58 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Main.py, line 43)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-50-58-16857.html
Thu Jan 12 21:50:58 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Main.py, line 43)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-50-58-11576.html
Thu Jan 12 21:51:12 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'Route' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-51-12-79855.html
Thu Jan 12 21:51:12 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'Route' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-51-12-78389.html
Thu Jan 12 21:51:30 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-51-30-13646.html
Thu Jan 12 21:51:30 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-51-30-10284.html
Thu Jan 12 21:52:49 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-52-49-83334.html
Thu Jan 12 21:52:49 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-52-49-17846.html
Thu Jan 12 21:52:56 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-52-56-48146.html
Thu Jan 12 21:52:56 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-52-56-47569.html
Thu Jan 12 21:54:22 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-54-22-38284.html
Thu Jan 12 21:54:22 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-54-22-95847.html
Thu Jan 12 21:55:50 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'startswith',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-55-50-13365.html
Thu Jan 12 21:56:11 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'NotFoundError' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-56-11-41029.html
Thu Jan 12 21:56:11 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-56-11-99734.html
Thu Jan 12 21:57:08 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'query' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-57-08-86181.html
Thu Jan 12 21:57:08 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-57-08-45268.html
Thu Jan 12 21:57:47 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-57-47-62251.html
Thu Jan 12 21:57:55 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'startswith',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-57-55-84024.html
Thu Jan 12 21:59:31 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-59-31-84451.html
Thu Jan 12 21:59:42 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-59-42-30846.html
Thu Jan 12 21:59:49 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-21-59-49-19884.html
Thu Jan 12 22:00:43 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-00-43-32438.html
Thu Jan 12 22:00:43 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-00-43-74747.html
Thu Jan 12 22:02:22 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'getController',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-02-22-94824.html
Thu Jan 12 22:02:22 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-02-22-32286.html
Thu Jan 12 22:02:36 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'getController',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-02-36-47467.html
Thu Jan 12 22:02:36 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-02-36-60736.html
Thu Jan 12 22:02:52 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-02-52-51599.html
Thu Jan 12 22:17:42 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-17-42-56001.html
Thu Jan 12 22:17:42 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-17-42-55238.html
Thu Jan 12 22:17:46 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-17-46-60270.html
Thu Jan 12 22:17:47 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-17-47-48726.html
Thu Jan 12 22:17:54 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-17-54-92722.html
Thu Jan 12 22:17:54 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-17-54-51606.html
Thu Jan 12 22:18:16 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-18-16-86564.html
Thu Jan 12 22:18:16 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-18-16-47529.html
Thu Jan 12 22:18:20 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-18-20-10237.html
Thu Jan 12 22:18:20 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-18-20-66110.html
Thu Jan 12 22:18:51 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-18-51-68420.html
Thu Jan 12 22:18:51 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-18-51-24373.html
Thu Jan 12 22:36:37 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-36-37-84412.html
Thu Jan 12 22:36:37 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-36-37-35904.html
Thu Jan 12 22:43:57 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-43-57-36287.html
Thu Jan 12 22:43:57 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-43-57-60182.html
Thu Jan 12 22:44:25 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-44-25-77139.html
Thu Jan 12 22:44:25 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-44-25-60317.html
Thu Jan 12 22:45:57 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-45-57-57359.html
Thu Jan 12 22:45:57 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-45-57-53527.html
Thu Jan 12 22:46:00 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-46-00-35150.html
Thu Jan 12 22:46:01 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-46-01-57284.html
Thu Jan 12 22:46:03 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-46-03-32446.html
Thu Jan 12 22:46:03 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-46-03-92180.html
Thu Jan 12 22:46:06 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-46-06-57062.html
Thu Jan 12 22:46:06 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-46-06-12803.html
Thu Jan 12 22:47:25 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-47-25-25454.html
Thu Jan 12 22:47:25 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-47-25-50907.html
Thu Jan 12 22:47:28 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-47-28-63395.html
Thu Jan 12 22:47:28 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-47-28-63293.html
Thu Jan 12 22:47:31 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-47-31-94146.html
Thu Jan 12 22:47:31 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-12-22-47-31-20975.html
Fri Jan 13 13:58:17 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-13-58-17-68090.html
Fri Jan 13 13:58:17 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-13-58-17-94420.html
Fri Jan 13 13:58:25 2006,Main.py,../dist/servlets/restricted/Main.py,BaseDatabase.NotFoundError,,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-13-58-25-11502.html
Fri Jan 13 13:58:25 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-13-58-25-14875.html
Fri Jan 13 14:00:04 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.NameError,global name 'NotFoundError' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-00-04-15262.html
Fri Jan 13 14:00:04 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-00-04-83220.html
Fri Jan 13 14:05:28 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-05-28-18523.html
Fri Jan 13 14:08:23 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-08-23-96966.html
Fri Jan 13 14:08:29 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-08-29-51440.html
Fri Jan 13 14:08:29 2006,Main.py,../dist/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-08-29-65618.html
Fri Jan 13 14:10:42 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-10-42-93624.html
Fri Jan 13 14:10:42 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-10-42-20173.html
Fri Jan 13 14:46:03 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.NameError,global name 'name' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-46-03-63725.html
Fri Jan 13 14:46:03 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-46-03-22600.html
Fri Jan 13 14:46:44 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.NameError,global name 'name' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-46-44-85648.html
Fri Jan 13 14:46:44 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-46-44-57098.html
Fri Jan 13 14:46:52 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-46-52-31739.html
Fri Jan 13 14:49:07 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-49-07-49635.html
Fri Jan 13 14:49:24 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-49-24-41271.html
Fri Jan 13 14:49:37 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-14-49-37-73665.html
Fri Jan 13 15:42:39 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.ImportError,No module named Index,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-15-42-39-84537.html
Fri Jan 13 15:42:39 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-15-42-39-87948.html
Fri Jan 13 15:44:40 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-15-44-40-55821.html
Fri Jan 13 15:44:40 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-15-44-40-21473.html
Fri Jan 13 16:54:33 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'aite',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-54-33-96389.html
Fri Jan 13 16:54:33 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-54-33-99139.html
Fri Jan 13 16:54:39 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'site',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-54-39-33237.html
Fri Jan 13 16:54:39 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-54-39-36452.html
Fri Jan 13 16:54:50 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'site',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-54-50-77147.html
Fri Jan 13 16:54:50 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-54-50-88691.html
Fri Jan 13 16:55:23 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-55-23-45295.html
Fri Jan 13 16:55:23 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-16-55-23-63384.html
Fri Jan 13 17:04:30 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-04-30-75111.html
Fri Jan 13 17:05:31 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-05-31-12485.html
Fri Jan 13 17:05:49 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-05-49-65523.html
Fri Jan 13 17:06:36 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-06-36-38843.html
Fri Jan 13 17:07:26 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-07-26-52989.html
Fri Jan 13 17:08:44 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-08-44-70348.html
Fri Jan 13 17:08:51 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-08-51-50679.html
Fri Jan 13 17:09:43 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-09-43-26160.html
Fri Jan 13 17:10:16 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-10-16-99914.html
Fri Jan 13 17:10:48 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-10-48-68125.html
Fri Jan 13 17:10:53 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-10-53-35670.html
Fri Jan 13 17:10:54 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-10-54-91106.html
Fri Jan 13 17:11:01 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-11-01-71241.html
Fri Jan 13 17:11:48 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-11-48-28959.html
Fri Jan 13 17:13:16 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.TypeError,'NoneType' object is not callable,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-13-16-82392.html
Fri Jan 13 17:13:16 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-13-16-67752.html
Fri Jan 13 17:27:14 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,Component instance has no attribute 'frameworkLocation',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-27-14-50555.html
Fri Jan 13 17:27:14 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-27-14-99650.html
Fri Jan 13 17:28:36 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.ImportError,cannot import name Framework,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-28-36-97430.html
Fri Jan 13 17:28:36 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.ImportError,cannot import name Framework,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-28-36-79669.html
Fri Jan 13 17:29:05 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Component.py, line 10)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-29-05-44382.html
Fri Jan 13 17:29:05 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.SyntaxError,"invalid syntax (Component.py, line 10)",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-29-05-65967.html
Fri Jan 13 17:29:18 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.NameError,global name 'checkLocation' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-29-18-99112.html
Fri Jan 13 17:29:19 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-29-19-15803.html
Fri Jan 13 17:29:41 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.NameError,global name 'name' is not defined,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-29-41-12648.html
Fri Jan 13 17:29:41 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-29-41-73262.html
Fri Jan 13 17:30:05 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-30-05-56956.html
Fri Jan 13 17:30:05 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-30-05-25671.html
Fri Jan 13 17:35:17 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-35-17-25850.html
Fri Jan 13 17:35:17 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-35-17-22118.html
Fri Jan 13 17:35:25 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-35-25-70712.html
Fri Jan 13 17:35:26 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-35-26-42752.html
Fri Jan 13 17:37:44 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-37-44-82992.html
Fri Jan 13 17:38:11 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-38-11-37805.html
Fri Jan 13 17:38:55 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.IndexError,list index out of range,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-38-55-83954.html
Fri Jan 13 17:38:55 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-38-55-21343.html
Fri Jan 13 17:39:53 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-39-53-74123.html
Fri Jan 13 17:40:28 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-40-28-47619.html
Fri Jan 13 17:41:06 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-41-06-41557.html
Fri Jan 13 17:42:23 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-42-23-72497.html
Fri Jan 13 17:42:52 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-42-52-41983.html
Fri Jan 13 17:42:52 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-42-52-27907.html
Fri Jan 13 17:44:59 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-44-59-73555.html
Fri Jan 13 17:45:00 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-45-00-21992.html
Fri Jan 13 17:46:33 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-46-33-75223.html
Fri Jan 13 17:46:34 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-46-34-44861.html
Fri Jan 13 17:47:52 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-47-52-56129.html
Fri Jan 13 17:47:52 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-47-52-52399.html
Fri Jan 13 17:48:07 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-48-07-10247.html
Fri Jan 13 17:48:07 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-48-07-37244.html
Fri Jan 13 17:49:04 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-49-04-20989.html
Fri Jan 13 17:49:51 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'str' object has no attribute 'serialize',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-49-51-34828.html
Fri Jan 13 17:49:51 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-49-51-52727.html
Fri Jan 13 17:50:30 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-50-30-92842.html
Fri Jan 13 17:52:23 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-52-23-60751.html
Fri Jan 13 17:53:58 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-53-58-38641.html
Fri Jan 13 17:54:13 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-54-13-61935.html
Fri Jan 13 17:54:29 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-54-29-64316.html
Fri Jan 13 17:56:03 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-56-03-83597.html
Fri Jan 13 17:56:44 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-56-44-15798.html
Fri Jan 13 17:57:14 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-17-57-14-12847.html
Fri Jan 13 18:00:13 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-00-13-62363.html
Fri Jan 13 18:21:07 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-21-07-64487.html
Fri Jan 13 18:21:22 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-21-22-93304.html
Fri Jan 13 18:21:29 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-21-29-10686.html
Fri Jan 13 18:21:49 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-21-49-94700.html
Fri Jan 13 18:24:29 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-24-29-91123.html
Fri Jan 13 18:24:46 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-24-46-10308.html
Fri Jan 13 18:24:46 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-24-46-42359.html
Fri Jan 13 18:24:49 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.UnboundLocalError,local variable 'db' referenced before assignment,/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-24-49-32335.html
Fri Jan 13 18:24:49 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-24-49-51096.html
Fri Jan 13 18:36:10 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-36-10-21677.html
Fri Jan 13 18:36:10 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-36-10-95451.html
Fri Jan 13 18:36:13 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-36-13-24839.html
Fri Jan 13 18:36:13 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-36-13-43776.html
Fri Jan 13 18:36:58 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.AttributeError,'NoneType' object has no attribute 'applyStylesheet',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-36-58-89273.html
Fri Jan 13 18:36:59 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-36-59-34690.html
Fri Jan 13 18:37:15 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-37-15-54559.html
Fri Jan 13 18:37:15 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-13-18-37-15-42548.html
Thu Jan 19 14:02:02 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-19-14-02-02-94593.html
Thu Jan 19 14:02:02 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-01-19-14-02-02-93219.html
Thu Feb  9 00:37:25 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-37-25-76268.html
Thu Feb  9 00:37:25 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-37-25-69633.html
Thu Feb  9 00:45:03 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'books',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-03-56123.html
Thu Feb  9 00:45:04 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-04-85973.html
Thu Feb  9 00:45:15 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.TypeError,"xmlParseDoc() argument 1 must be string without null bytes or None, not str",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-15-70286.html
Thu Feb  9 00:45:16 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-16-95668.html
Thu Feb  9 00:45:30 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.TypeError,"xmlParseDoc() argument 1 must be string without null bytes or None, not str",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-30-65784.html
Thu Feb  9 00:45:30 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-30-52898.html
Thu Feb  9 00:45:39 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.TypeError,"xmlParseDoc() argument 1 must be string without null bytes or None, not str",/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-39-32299.html
Thu Feb  9 00:45:39 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-45-39-41490.html
Thu Feb  9 00:46:25 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-46-25-85632.html
Thu Feb  9 00:46:25 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-46-25-44769.html
Thu Feb  9 00:46:48 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-46-48-57224.html
Thu Feb  9 00:46:48 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-46-48-69526.html
Thu Feb  9 00:47:49 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-47-49-98286.html
Thu Feb  9 00:47:49 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-47-49-97550.html
Thu Feb  9 00:48:40 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-48-40-65522.html
Thu Feb  9 00:48:39 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-48-39-23773.html
Thu Feb  9 00:49:05 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'site',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-05-74371.html
Thu Feb  9 00:49:05 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-05-58071.html
Thu Feb  9 00:49:16 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-16-22592.html
Thu Feb  9 00:49:16 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-16-70368.html
Thu Feb  9 00:49:23 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-23-16799.html
Thu Feb  9 00:49:23 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-23-16413.html
Thu Feb  9 00:49:30 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-30-58860.html
Thu Feb  9 00:49:30 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-30-14142.html
Thu Feb  9 00:49:55 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-55-35330.html
Thu Feb  9 00:49:55 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-49-55-92903.html
Thu Feb  9 00:51:08 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-51-08-20976.html
Thu Feb  9 00:51:08 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-00-51-08-67051.html
Thu Feb  9 01:04:22 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-04-22-87776.html
Thu Feb  9 01:04:22 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-04-22-21355.html
Thu Feb  9 01:04:44 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-04-44-37680.html
Thu Feb  9 01:04:44 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-04-44-81100.html
Thu Feb  9 01:05:11 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-05-11-52004.html
Thu Feb  9 01:05:11 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-05-11-50078.html
Thu Feb  9 01:05:24 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-05-24-28377.html
Thu Feb  9 01:05:24 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-05-24-34772.html
Thu Feb  9 01:06:34 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-06-34-97028.html
Thu Feb  9 01:06:34 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-06-34-38459.html
Thu Feb  9 01:07:12 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'~kstaken',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-07-12-20189.html
Thu Feb  9 01:07:12 2006,Main.py,../src/servlets/restricted/Main.py,exceptions.KeyError,'favicon.ico',/Users/kstaken/Workspace/Syncato/syncato/webware-instance/ErrorMsgs/Error-Main.py-2006-02-09-01-07-12-61873.html
